### ISSUE TITLE
Documentation needs update: Application\Sonata\ClassificationBundle not found

### ISSUE THREAD

**Issue by janjango** [EtonDigital/EDBlogBundle#9]
I just install the bundle and follow the doc.
But while executing `php app/console as:du --env=prod`
I get `Application\Sonata\ClassificationBundle not found ...`
I fixed it by following the`#step-4-sonatamediabundle-installation-and-configuration`
In Step 2 : #29-user-repository
There is a typo: AppUserRepository  shoulld be  UserRepository.

After those things, it is awesome!

It will be good to enable blog header and footer configuration.
Thanks!

**Comment by milosmoto** [comment]
Hi Jacques,

thanks for update... If you follow all steps and install sonatamedia bundle there shouldn't be that problem with assetic:dump

Assetic dump is the last step as I can see.
Did you skip #step 4 when you integrate this bundle?

Thanks for idea regarding header and footer...

**Comment by janjango** [comment]
Yes I follow this step:
It sems that the ClassificationBundle config step is missed:
- I add  `new Sonata\ClassificationBundle\SonataClassificationBundle(), in the AppKernel`
- and generate it: `php app/console sonata:easy-extends:generate --dest=src S
  onataClassificationBundle`
- and finaly add in appKernel: `new Application\Sonata\ClassificationBundle\ApplicationSonataClassificationBundle(),`

And that is all I do. 
Or do you mean that Assetic dump should do these staff for me?

**Comment by milosmoto** [comment]
Hi Jacques,
No I don't mean that assetic dump will make it for you. Sonata is completely separated bundle and we are just using them for administration part.

We need to update documentation with this, reason is changes on sonata bundle where classification bundle is required for sonata now....It wasn't required before, when we create this bundle.

You make it correct with installation of classification bundle, otherwise you should use old reference of sonata bundle. I hope now everything works for you?

**Comment by janjango** [comment]
All right now. Thanks!
